name = "GenomePermutations"
uuid = "332f1fbc-14a8-4e72-b09d-ec057a6da7c2"
authors = ["Simone De Angelis <simone.deangelis@qmul.ac.uk> <side97.11+jl@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
